version: '2.1'

services:
  awsmessaging:
    image: awsmessaging
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js